### ISSUE TITLE
this sucks

### ISSUE THREAD

**Issue by TCMine** [OneAndonlyFinbar/dbm-leaderboard#1]
it sucks
why my hours not update 
delete 

Attach files by dragging & dropping, selecting or pasting them.
Styling with Markdown is supported
[ Styling with Markdown is supported](https://docs.github.com/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax)
Remember, contributions to this repository should follow our [GitHub Community Guidelines](https://docs.github.com/articles/github-community-guidelines).
Assignees
No one assigned
Labels
None yet
Projects
None yet
Milestone
No milestone
Development
Shows branches and pull requests linked to this issue.

Helpful resources
[GitHub Community Guidelines](https://docs.github.com/articles/github-community-guidelines)

**Comment by OneAndonlyFinbar** [comment]
idek lol
